### ISSUE TITLE
librosa.display.waveplot not work

### ISSUE THREAD

**Issue by bzvew** [stevetjoa/stanford-mir#37]
`plt.figure(figsize=(12, 4))   librosa.display.waveplot(x, sr=sr)`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-b957c8af8c56> in <module>()
      1 plt.figure(figsize=(12, 4))
----> 2 librosa.display.waveplot(x, sr=sr)

/Library/Python/2.7/site-packages/librosa/display.pyc in waveplot(y, sr, max_points, x_axis, offset, max_sr, **kwargs)
    438     axes = plt.gca()
    439 
--> 440     kwargs.setdefault('color', next(axes._get_lines.prop_cycler)['color'])
    441 
    442     locs = offset + core.frames_to_time(np.arange(len(y_top)),

AttributeError: _process_plot_var_args instance has no attribute 'prop_cycler'

**Comment by stevetjoa** [comment]
I don't see anything wrong with the code. If I had to guess, `x` may not be well formed. If the problem persists, you may want to raise this issue with @librosa.

**Comment by bzvew** [comment]
x is ok for the subsequent analysis, and thank you for your suggestion.

**Comment by maxwellmckinnon** [comment]
I'm getting this same issue on even a known good small x

@bzvew Did you find a solution?

I've found it works in python3, but unfortunately that's not a solution for this particular project :(
