### ISSUE TITLE
sklearn.cross_validation changed to sklearn.model_selection

### ISSUE THREAD

**Issue by kyungyunlee** [stevetjoa/stanford-mir#40]
In 2. Cross Validation of Machine Learning section, currently `acc  = sklearn.cross_validation.cross_val_score(model, training_features, training_labels, cv=5)` is being used, but in scikit-learn version starting at 0.18, this is changed to `sklearn.model_selection.cross_val_score()`. 
Perhaps add if/else statement for importing the correct `cross_val_score() ` function depending on these different version?

Thanks for the nice tutorial :)

**Comment by stevetjoa** [comment]
Thanks, you are right. In fact, there is a lot more on cross validation and parameter search using scikit-learn that we should include in the notebooks.

I will get to that, or you are welcome to make a pull request.

**Comment by kyungyunlee** [comment]
I surely will ;)
By the way, there are 2 different models defined: KNN and logistic regression. 
I guess we should just select one?

**Comment by stevetjoa** [comment]
Thanks for the pull request!
