### ISSUE TITLE
Google Collaboratory Notebook

### ISSUE THREAD

**Issue by johntheo** [stevetjoa/stanford-mir#45]
1. Create a notebook in [Google Collaboratory](https://colab.research.google.com) which:
- Clone this repository
- Save the cloned files in the user Google Drive (see this [tutorial](https://medium.com/deep-learning-turkey/google-colab-free-gpu-tutorial-e113627b9f5d))

2. Update the **Readme.md** with the instructions to import and run the notebook in Google Collaboratory

The notebook should be shared for other users copy to their own Google Drive. 
So, there is no need to a person interested to run the notebooks install  Anaconda in his computer. All notebook could be executed online.

**Comment by stevetjoa** [comment]
Thanks for the suggestion. I have looked into Google Colab. It's okay for some users and environments, and I can add some instructions in the README. But it adds the step of needing to install `librosa` and other packages inside the notebook environment itself which seems undesirable to me. There are many interface differences with locally hosted Jupyter, as well.
