### ISSUE TITLE
python3 && python2

### ISSUE THREAD

**Issue by dianyo** [stevetjoa/stanford-mir#48]
Hello, 
    Your codes are actually written in python2. But in the readme, you told user to download anaconda python3.x. This causes SyntaxError in every print statement, and it's really annoying...

**Comment by stevetjoa** [comment]
You're partially right. The older notebooks use Python 2 syntax, and the newer notebooks use Python 3 syntax. I have not gotten to updating all of the notebooks, but you are welcome to submit pull requests.

**Comment by katpasalo** [comment]
Submitted a pull request for the print statements!
